name: flutter_email_sender_web
description: Web platform implementation of flutter_email_sender.
publish_to: none
version: 1.0.0
homepage: https://github.com/sidlatau/flutter_email_sender
repository: https://github.com/sidlatau/flutter_email_sender/tree/master/packages/flutter_email_sender_web
issue_tracker: https://github.com/sidlatau/flutter_email_sender/issues

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.8"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_email_sender_platform_interface:
    path: ../flutter_email_sender_platform_interface
  url_launcher: ^6.3.2

flutter:
  plugin:
    implements: flutter_email_sender
    platforms:
      web:
        pluginClass: FlutterEmailSenderWeb
        fileName: flutter_email_sender_web.dart

topics:
  - email
  - web
  - mailto
  - federation
